name: Tail-to-Tail Companion

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install axios
        run: npm install axios

      - name: Run Tail-to-Tail
        run: node bridge/map-companion.js
        env:
          MAP_AVIA_TOKEN: ${{ secrets.MAP_AVIA_TOKEN }}
          AVIA_MAP_TOKEN: ${{ secrets.AVIA_MAP_TOKEN }}